version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: afrin123/aashika:2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
         - target: 8889
           published: 8889
           protocol: tcp
           mode: host

     
