version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: afrin123/aashika:97
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
     ports:
        -"8889:8889"
     
