version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: afrin123/aashika:2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
     ports:
        - "8889:8889"
     volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
       
